### ISSUE TITLE
Pass a script consists of multiple queries 

### ISSUE THREAD

**Issue by pratnaparkhi2000** [nalbury/promql-cli#20]
Hi, thank you for this tool : )
I want to write a script which will be consisting of multiple queries and pass it instead of throwing one by one. Is it possible?

**Comment by nalbury** [comment]
That's an interesting idea, but I'm not sure I know exactly what you mean? 

Off the top of my head, doing what you're describing is already possible with some shell scripting.

given a file of queries, one per line (in this case called queries.promql):
```
kube_pod_info{namespace="kube-system"}
sum(go_goroutines) by (namespace)
```
```
while read -r query; do promql  "$query" --output json >> results.json; done < queries.promql
```

That said, I'm not aware of any concepts/patterns for transactions or scripting in prometheus so maybe I'm missing something?

**Comment by pratnaparkhi2000** [comment]
Hi @nalbury , 
As I am new to linux, I did not know how to read the .promql file and store the results in another. This command worked. Thank you : ) I want to know if in the same way, can I store it in another formats( like .txt, .pout, etc). Feel free to close the issue after this :)

**Comment by nalbury** [comment]
At the moment the `promql`cli supports:
- table (tab separated output with padding) output for instance vector queries (the default)
- ascii graph output for range queries (the default)
- json output for all queries
- csv output for all queries

These can be set with the `—output` flag and then can be written to a file extension of your choosing.

For example to change my previous example loop from json output to csv:

```
while read -r query; do promql  "$query" --output csv >> results.csv; done < queries.promql
```

Or, for the table output you could do something like:

```
while read -r query; do echo “### $query ###” >> results.txt && promql  "$query" >> results.txt; done < queries.promql
```
Which will echo a “header” before each table in results.txt to keep them somewhat organized. 

If you’re looking for more linux/shell scripting tips and tricks I highly recommend anything by Julia Evans (https://wizardzines.com). I still reference her zines all the time.

Going to close this for now but feel free to reopen if you have any `promql` specific requests or issues.

Thanks!
