### ISSUE TITLE
Proxy support?

### ISSUE THREAD

**Issue by tallpsmith** [nalbury/promql-cli#24]
This is perhaps more a question than a bug, but I can't seem to get this utility to work against a Prometheus setup in a large corporate environment that uses corporate proxies & SSO authentication.

The Prometheus service I am trying to query has a non-SSO user account I can successfully use Basic Auth against using `curl -u` - I can get configuration and metric/labels manually if I can hand-wire the `curl` command.  So I know the auth is working, and I know that `curl` is successfully using our `HTTP_PROXY` environment variables.

When I use `promql` here (built from source, tip of `HEAD`) I provide the `--auth-type Basic --auth-credentials-file` options where the credential file has the valid credentials.  I've tried both `curl -u` format and `| base64` formats.

The response from the tool though, looks more like a Proxy-related error:

```
❯ build/bin/darwin/amd64/promql --tls_config.insecure_skip_verify  --auth-type Basic --auth-credentials-file /tmp/prom.token   --host https://prometheus.dev........... metrics
Error querying metadata endpoint: Get "https://< non-Prometheus HOST|URL that clearly indicates a redirection to our SSO service > : x509: certificate signed by unknown authority
```

I don't believe it's the TLS certificate error (I'm using `--tls_config.insecure_skip_verify` just in case) - it feels like a Proxy error.

Tracing through the Go code (not super familiar with Go though), it's using the underlying Go `http` library code which should auto-detect the Proxy.

I'm not sure if anyone has some further suggestions to try.  Like the look of this tool!

**Comment by nalbury** [comment]
Sorry for the delayed response here, between my day job and moving I haven't had as much time to work on this as I'd like.

As to the issue you mentioned, the cli is admittedly a little light on tests so recent changes to support auth may not be 100% functional. There's another issue [here](https://github.com/nalbury/promql-cli/issues/25) which was recently opened that also indicates some issues with bearer tokens, so as soon as I have some time to dig in, I'll set up some real integration testing and figure this out.

Thanks!
