### ISSUE TITLE
metrics command gets the query-error

### ISSUE THREAD

**Issue by mpiexec** [nalbury/promql-cli#30]
Hello, everything work good except getting list of metrics
```
$ promql metrics
error querying series endpoint: bad_data: 1:1: parse error: unexpected end of input
```
Any suggestions? Thank you

**Comment by chukmunnlee** [comment]
I've created a PR to this issue. 
You can find the binaries [here](https://github.com/chukmunnlee/promql-cli)

**Comment by mpiexec** [comment]
@chukmunnlee 
re-built from your repo, and now I've got empty result:
```
$ promql metrics
METRICS
$
```

**Comment by chukmunnlee** [comment]
If you don't set any job name it'll default to prometheus

If you're trying to get the list of metrics from job_name: node do this

promql metrics node

**Comment by mpiexec** [comment]
@chukmunnlee thx, it works 👍🏻

**Comment by chukmunnlee** [comment]
@mpiexec 
I've have added a new option `targets` which list all the configured targets (job_name) in your prometheus.yml file

**Comment by nalbury** [comment]
@chukmunnlee can you elaborate on how your PR addresses this issue? as far as I can tell you've introduced a default query arg with 0 documentation (or even help msg updates) along with other changes not mentioned here. 

In my opinion the cli should simply return a more useful error here vs introducing an assumed default query string. 

The targets command is a useful addition but unfortunately its wrapped up in the same PR so I will reimplement with full documentation.
