### ISSUE TITLE
Build release artifacts (promql) for linux amd64

### ISSUE THREAD

**Issue by ksatchit** [nalbury/promql-cli#7]
At the outset, thanks @nalbury for building this really nice tool! It would be great if we had the readme cover build instructions & also if a Linux binary is pushed as a release artifact.

**Comment by perlun** [comment]
Completely agree. I was also thinking about testing this but as I run Linux on my work machine, a `linux-amd64` binary would be highly appreciated.

@nalbury If you don't have any hardware for building the Linux releases, using GitHub Actions for building it could be an idea I guess.

**Comment by nalbury** [comment]
Yea at the moment none of the builds are automated but I can ship a linux build no problem:
```
curl -o /usr/local/bin/promql https://promql-cli.s3.amazonaws.com/latest/linux/promql && chmod +x /usr/local/bin/promql
```

I'll add this to the README later but building should be as easy as:
```
git clone https://github.com/nalbury/promql-cli.git

**Comment by perlun** [comment]
Thanks, sounds good @nalbury.

**Comment by nalbury** [comment]
I set up build CI that will build amd64 versions of the linux and macOS binaries. The [latest release](https://github.com/nalbury/promql-cli/releases/tag/v0.2.1) should have both available for download.

**Comment by perlun** [comment]
Thanks @nalbury
